[project]
name = "fastapi-daily"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.133.1",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
]
